#!/usr/bin/env node

start();
function start () {
  'use strict';

  // Handle ouput and errors caused by running commands
  function outputHandler (error, stdout, stderr) {
    console.log('stdout: ' + stdout);
    console.log('stderr: ' + stderr);
    if (error !== null) {
      console.log('exec error: ' + error);
    }
  };

  // Execute the command
  function exec (commandString) {
    const execute = require('child_process').exec;
    
    execute(commandString, outputHandler);
  };

  main();
  function main () {
    exec("git add .");
    exec("git commit");
    exec("git push");
  };
};
